### ISSUE TITLE
Error: Expected EOF, COLUMN_SEPARATOR, LINE_SEPARATOR; received

### ISSUE THREAD

**Issue by kemicofa** [vslinko/deno-csv#11]
This CSV was generated from google spreadsheets and should be valid but failing to parse it properly. 
The line 2, character 297 corresonds to a closing `"`. If I add a `,` after it then it parses the line properly.

I'm also parsing this file on my mac and the EOL are `^M$`.

Is this a bug?

```
 (line 2, character 298)ise) Error: Expected EOF, COLUMN_SEPARATOR, LINE_SEPARATOR; received
            new Error(
            ^
    at CSVReader.parseCycle (https://deno.land/x/csv@v0.7.0/reader.ts:364:13)
    at CSVReader.read (https://deno.land/x/csv@v0.7.0/reader.ts:173:12)
    at https://deno.land/x/csv@v0.7.0/reader.ts:631:21
    at new Promise (<anonymous>)
    at CSVRowReader.next (https://deno.land/x/csv@v0.7.0/reader.ts:628:17)
    at readCSVObjects (https://deno.land/x/csv@v0.7.0/reader.ts:832:20)
    at async Command.create (file:///Users/XXX/Documents/private/yotee/cli/actions/create/create.ts:33:22)
```

[example.csv](https://github.com/vslinko/deno-csv/files/7436575/example.csv)

**Comment by tv42** [comment]
I'm getting the same error from Google Sheets export having CR NL line endings:

```
Error: Expected EOF, COLUMN_SEPARATOR, LINE_SEPARATOR; received \r (line 2, character 743)
```

**Comment by tv42** [comment]
This solved my problem:

```
  const csv = readCSVObjects(reader, {lineSeparator: "\r\n"});
```

**Comment by tv42** [comment]
Would there be any harm in defaulting to accepting both `\n` and `\r\n`?

**Comment by vslinko** [comment]
I have a lineSeparator autodetection in my backlog, but it's hard to do it in an efficient way.
For now, I have improved the error message:

```
error: Uncaught (in promise) Error: Expected EOF, COLUMN_SEPARATOR, LINE_SEPARATOR; received \r (line 1, character 86)
Perhaps you need to add the setting lineSeparator: "\r\n"
https://git.io/JDTDS
          this.onError(new Error(msg));
                       ^
```
