### ISSUE TITLE
Seems that you need to update you dependencies?

### ISSUE THREAD

**Issue by Kayxue** [vslinko/deno-csv#14]
Code:
```ts
import { axiod, readCSVObjects } from "../Dependencies.ts";

axiod
    .get("https://data.nhi.gov.tw/resource/mask/maskdata.csv")
    .then(async ({ data }) => {
        for await (const obj of readCSVObjects(data)) {
            console.log(obj);
        }
    });
```

```
error: Uncaught (in promise) TypeError: r.read is not a function
    const result = await r.read(b);
                           ^
    at iterateReader (https://deno.land/std@0.117.0/streams/conversion.ts:432:28)
    at iterateReader.next (<anonymous>)
    at CSVReader.readMoreData (https://deno.land/x/csv@v0.7.3/reader.ts:230:55)
    at CSVReader.parseCycle (https://deno.land/x/csv@v0.7.3/reader.ts:282:20)
    at CSVReader.read (https://deno.land/x/csv@v0.7.3/reader.ts:174:12) 
    at https://deno.land/x/csv@v0.7.3/reader.ts:633:21
    at new Promise (<anonymous>)
    at CSVRowReader.next (https://deno.land/x/csv@v0.7.3/reader.ts:630:17)
    at readCSVObjects (https://deno.land/x/csv@v0.7.3/reader.ts:834:20) 
    at readCSVObjects.next (<anonymous>)
```

**Comment by vslinko** [comment]
@Kayxue thank you for the feedback.

`readCSVObjects` accepts `Deno.Reader` interface as the first argument, not a string.
You can use `StringReader` from standard library to wrap a string.

```
import axiod from "https://deno.land/x/axiod/mod.ts";
import { readCSVObjects } from "./mod.ts";
import { StringReader } from "https://deno.land/std@0.133.0/io/mod.ts";

axiod
    .get("https://data.nhi.gov.tw/resource/mask/maskdata.csv")
    .then(async ({ data }) => {
        for await (const obj of readCSVObjects(new StringReader(data))) {
            console.log(obj);
        }
    });
```
