### ISSUE TITLE
`this.writer.write is not a function` error

### ISSUE THREAD

**Issue by eric-gade** [vslinko/deno-csv#18]
Hello!
  
When attempting to run something like the following:
```
import { writeCSV } from "https://deno.land/x/csv/mod.ts";

writeCSV("./test.csv", [["hello", "there"]]);
```
  
I am receiving the following error:
```
error: Uncaught (in promise) TypeError: this.writer.write is not a function
        await this.writer.write(
                          ^
    at CSVWriter._writeCellAsyncIterable (https://deno.land/x/csv@v0.8.0/writer.ts:129:27)
    at async writeCSV (https://deno.land/x/csv@v0.8.0/writer.ts:179:7)
```

**Comment by vslinko** [comment]
Hi @eric-gade 

You need to use [Deno.Writer](https://deno.land/api?s=Deno.Writer) as the first argument, eg: https://github.com/vslinko/deno-csv#write-csv-file
