### ISSUE TITLE
Cannot use generator with writeCSV

### ISSUE THREAD

**Issue by jeiea** [vslinko/deno-csv#22]
```
await writeCSV(csv, csvRows());
function* csvRows(subtitles: Subtitle[]): Generator<string[]>;
```

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Symbol.asyncIterator)')
  return !!iter[Symbol.asyncIterator];
               ^
    at isAsyncIterable (https://deno.land/x/csv@v0.9.1/utils.ts:28:16)
    at CSVWriter.writeCell (https://deno.land/x/csv@v0.9.1/writer.ts:66:9)
    at writeCSV (https://deno.land/x/csv@v0.9.1/writer.ts:179:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by vslinko** [comment]
@jeiea hi! thank you for the feedback.

Unfortunately, I can't reproduce the issue. It looks like your generator yields undefined, not an array of strings.

```js
    const buf = new Buffer();

    function* syncRows(): Generator<string[]> {
      yield ["a", "b"];
      yield ["c", "d"];
      yield ["1", "2"];
    }

    await writeCSV(buf, syncRows());

    assertEquals(new TextDecoder().decode(buf.bytes()), `a,b\nc,d\n1,2`);
```

**Comment by jeiea** [comment]
I deleted that problematic code and can't recover them. Close it for now.
